version: "3.9"

services:
  order_service:
    build: ./services/shopbridge_order
    container_name: order_service
    ports:
      - "${ORDER_SERVICE_PORT:-3000}:80"
    volumes:
      - order_service_data:/app/Data
    depends_on:
      - product_service
      - logistics_service
    networks:
      - backend

  logistics_service:
    build: ./services/shopbridge_logistics
    container_name: logistics_service
    ports:
      - "${LOGISTICS_SERVICE_PORT:-8000}:80"
    volumes:
      - logistics_service_data:/app/Data
    networks:
      - backend

  product_service:
    build: ./services/shopbridge_product
    container_name: product_service
    ports:
      - "${PRODUCT_SERVICE_PORT:-5000}:5000"
    volumes:
      - product_service_data:/app/Data
    networks:
      - backend

volumes:
  order_service_data:
  logistics_service_data:
  product_service_data:

networks:
  backend:
    driver: bridge
