version: "3.9"

services:
  order_service:
    build: ./services/shopbridge_order/order_application
    container_name: order_service
    ports:
      - "${ORDER_SERVICE_PORT:-3000}:80"
    volumes:
      - order_service_data:/app/order_application/data
    depends_on:
      - product_service
      - logistics_service
    networks:
      - backend

  logistics_service:
    build: ./services/shopbridge_logistics/LogisticsAPI
    container_name: logistics_service
    ports:
      - "${LOGISTICS_SERVICE_PORT:-8000}:80"
    volumes:
      - logistics_service_data:/app/LogisticsAPI/Storage
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - backend

  product_service:
    build: ./services/shopbridge_product/ProductApplication
    container_name: product_service
    ports:
      - "${PRODUCT_SERVICE_PORT:-5000}:80"
    volumes:
      - product_service_data:/app/ProductApplication/Storage
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - backend

volumes:
  order_service_data:
  logistics_service_data:
  product_service_data:

networks:
  backend:
    driver: bridge