version: "3.9"

services:
  order_service:
    build: ./services/shopbridge_order/order_application
    container_name: order_service
    ports:
      - "${ORDER_SERVICE_PORT:-3000}:3000"
    volumes:
      - ./services/shopbridge_order/order_application/storage:/app/storage
    depends_on:
      - product_service
      - logistics_service
    networks:
      - backend
    env_file:
      - .env

  logistics_service:
    build: ./services/shopbridge_logistics/LogisticsAPI
    container_name: logistics_service
    ports:
      - "${LOGISTICS_SERVICE_PORT:-8000}:8000"
    volumes:
      - logistics_service_data:/app/Storage
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - backend
    env_file:
      - .env

  product_service:
    build: ./services/shopbridge_product/ProductApplication
    container_name: product_service
    ports:
      - "${PRODUCT_SERVICE_PORT:-5000}:5000"
    volumes:
      - product_service_data:/app/Storage
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - backend
    env_file:
      - .env

volumes:
  order_service_data:
  logistics_service_data:
  product_service_data:

networks:
  backend:
    driver: bridge
